<?php

namespace App\Repository;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getCompanyDetail($params){
            $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('c')->from($this->getEntityName(),'c')
                ->andWhere('c.isActive = 1');
            foreach ($params as $key => $value){
                $qb->andWhere("c.$key = :$key")->setParameter(":$key",$value);
            }
            return $qb->getQuery()->getOneOrNullResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
